# Generated by Django 5.2 on 2026-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='editorial_name',
            field=models.CharField(max_length=100),
        ),
    ]
