# Generated by Django 5.2 on 2026-07-20 20:06

from django.db import migrations, transaction

def forward_migrate_editorial(apps, schema):
    """
    Creates Editorials from Book data and assign them
    """

    # get historical models versions as suggested here
    # https://docs.djangoproject.com/en/5.2/topics/migrations/#historical-models
    Book = apps.get_model('bookstore', 'Book')
    Editorial = apps.get_model('bookstore', 'Editorial')

    # if the database is empty, theres no 
    # need to iterate over any tables
    if not Book.objects.exists():
        print("No book in the database, forwarding to the next migration")
        return

    # iterate over every book in a transaction to ensure 
    # database performance and th fact that data
    # will be rolled back in case of failure
    with transaction.atomic():
        for book in Book.objects.all():
            # get_or_create returns a tuple of (object, created) 
            # the second value won't be necessary this time
            # that's whay the wildcard variable _
            editorial, _ = Editorial.objects.get_or_create(
                # check for coincidences no matter case sensitive
                name__iexact=book.editorial_name,
                # lets keep the name with original capitalization
                defaults={
                    'name': book.editorial_name,
                    'address': book.editorial_address
                }
            )

            # assign editorial to book
            book.editorial = editorial
            book.save()

def reverse_migrate_editorial(apps, schema_editor):
    """
    Undo the migration, put back editorial data as
    text fields in Book and deletes editorials
    """

    Book = apps.get_model('bookstore', 'Book')
    Editorial = apps.get_model('bookstore', 'Editorial')

    # iterate over every book related to an editorial
    # in a transaction
    with transaction.atomic():
        # select_related add performance over database searching
        # when retrieving foreign-key relationships
        for book in Book.objects.select_related('editorial').all():
            if book.editorial:
                book.editorial_name = book.editorial.name
                book.editorial_address = book.editorial.address
                book.save()
    
    # remove all Editorial objects
    Editorial.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_editorial_book_editorial'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_migrate_editorial, 
            reverse_code=reverse_migrate_editorial
        )
    ]
