# Generated by Django 5.2 on 2026-07-20 21:02

from django.db import migrations, models


def ensure_all_books_have_editorial(apps, schema_editor):
    """
    Ensures all books have an editorial, if a book doesn't have
    any get assigned the first one, if no Editorial exists a default one
    is created
    """

    # get historical models
    Editorial = apps.get_model('bookstore', 'Editorial')
    Book = apps.get_model('bookstore', 'Book')

    # if the database is empty, go ahead 
    # to the next operations
    if not Book.objects.exists():
        print("No book in the database, forwarding to the next operations")
        return

    # get first Editorial object
    first_editorial = Editorial.objects.first()

    # if no editorials create a default one
    if not first_editorial:
        first_editorial = Editorial.objects.create(
            name='Default editorial',
            address='Default editorial address',
        )
    
    # get all books without editorials and update them
    books_without_editorial = Book.objects.filter(editorial__isnull=True)
    books_without_editorial.update(editorial=first_editorial)


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20260720_2006'),
    ]

    operations = [
        # ensure all books gets assigned an editorial
        migrations.RunPython(
            code=ensure_all_books_have_editorial,
            reverse_code=migrations.RunPython.noop # this operation shouldn't be reverted
        ),
        # set editorial field to non null
        migrations.AlterField(
            model_name='Book',
            name='editorial',
            field=models.ForeignKey(to='bookstore.editorial', on_delete=models.CASCADE)
        ),
        # remove old fields
        migrations.RemoveField(
            model_name='book',
            name='editorial_name'
        ),
        migrations.RemoveField(
            model_name='book',
            name='editorial_address'
        )
    ]
